#import = ["~/.cache/wal/colors-alacritty.toml"]
import = ["~/.config/alacritty/themes/carbonfox.toml"]

live_config_reload = true

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
dynamic_padding = true

[window.padding]
x = 1
y = 1

[cursor.style]
#blinking = "On"
shape = "Beam"

[font]
size = 10

builtin_box_drawing = true

normal = { family = "JetBrainsMono NF", style = "Semibold" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
